name: 'AWS SES Verify Sender Lambda'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: pwsh

permissions:
  checks: write

jobs:
  AWS_SES_LINT_AND_TEST:
    name: AWS SES Lint and Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Pipenv and dependencies
        run: |
          make install_dev

      - name: Run Linting
        run: |
          make lint
          $functionName = make func-name
          # If the Linting Report exits then there's linting errors, exit with 1, else 0

          if ((Test-Path -Path "build/${functionName}_lint_report.txt" -Type Leaf) -and ((Get-Item "build/${functionName}_lint_report.txt").Length -ne 0))
          {
            exit 1
          }

          exit 0

      - name: Run Tests
        run: |
          make test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/*.xml'
          annotate_only: true
